# Generated by Django 4.0.3 on 2022-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('short_description', models.TextField(default='SOME STRING', max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
