# Generated by Django 4.0.3 on 2022-03-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_category_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
