# Generated by Django 2.2.10 on 2022-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210413_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
