# Generated by Django 4.0.3 on 2022-03-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.TextField(default='Description', max_length=140),
        ),
    ]
