# Generated by Django 4.0.3 on 2022-05-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
